name: openagent_data_models
description: Data models for Open Agent software.
version: 1.3.0-b
homepage: https://gitlab.com/devopsafs/openagent/openagent_data_models
author: OpenAgent Team

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.15.7
  data_model:
    git:
      url: https://gitlab.com/dartrest/data_model.git
      ref: 'master'
  dartz: ^0.8.5

dev_dependencies:
  test: ^1.0.0
  mongo_dart: ^0.3.3
